export { default as Categories } from './categories'
export { default as Products } from './products'
export { default as ProductDetail} from './product-detail'
export { default as Orders } from './orders'
export { default as Cart } from './cart'
export { default as Auth } from './auth'
export { default as Setting } from './settings'
export { default as Profile } from './profile'